### ISSUE TITLE
Missing Dimensions & Fields

### ISSUE THREAD

**Issue by RefreshworksKIKI** [Gladior-B-V/channable-connector#1]
Because the standard dimensions are not available you cannot make a graph in data studio with the Channable connection. Dimension Needed is ('Date')
Fields Need are ('Revenue') ('Impressions') ('Users')

**Comment by zoedufrenne** [comment]
Hi,

These field are not available in the standard API of Channable.
The Date dimension is something we could build in the connector but ('Revenue') ('Impressions') ('Users') is not something we can build in the connector. 

We will put the date dimension on the roadmap and will let you know when this is added to the connector.

**Comment by zoedufrenne** [comment]
Hi,

We've made some updates.
In the connector we have date fields, such as 'created date offer', 'date order created', 'date order modified' & 'Modified date offer'. Another date field is not available in the Channable API.

For the field Revenue, we have the metric 'total price'. 
If you have any questions, please let us know!

Zoé du Frenne
